spring:
  application:
    name: CarManagementBackend
  datasource:
    url: jdbc:mysql://localhost:3306/car_management?useSSL=false&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12341234
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

